import os
import uuid
import logging
from pathlib import Path
from github import Github, GithubException
from src.tools.base import BaseTool
from src.config import settings

logger = logging.getLogger(__name__)

class SubmitToolToRepoTool(BaseTool):
    """
    Submits a dynamic tool to the GitHub repository as a Pull Request.
    """
    
    @property
    def name(self) -> str:
        return "submit_tool_pr"
    
    @property
    def description(self) -> str:
        return "將驗證過的新工具提交到 GitHub Repository 進行審核與保存。會自動建立 Branch 並發起 PR。"
    
    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "tool_name": {
                    "type": "string",
                    "description": "要提交的工具名稱"
                },
                "purpose": {
                    "type": "string",
                    "description": "工具用途說明"
                }
            },
            "required": ["tool_name", "purpose"]
        }

    async def execute(self, **kwargs) -> dict:
        tool_name = kwargs.get("tool_name")
        purpose = kwargs.get("purpose")
        
        if not tool_name or not purpose:
            return {"status": "error", "message": "Missing tool_name or purpose."}

        dynamic_dir = Path(__file__).parent.parent / "dynamic"
        filename = f"{tool_name}.py"
        file_path = dynamic_dir / filename
        
        if not file_path.exists():
            filename = f"dynamic_tool_{tool_name}.py"
            file_path = dynamic_dir / filename
        
        if not file_path.exists():
             return {"status": "error", "message": f"Tool file not found: {tool_name}"}

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                code_content = f.read()
        except Exception as e:
            return {"status": "error", "message": f"Failed to read tool file: {e}"}

        token = settings.COPILOT_GITHUB_TOKEN
        repo_name = settings.GITHUB_REPO_NAME
        
        if not token or not repo_name:
             return {"status": "error", "message": "Missing GitHub configuration (token or repo name)."}

        try:
            g = Github(token)
            repo = g.get_repo(repo_name)
            main_branch = repo.get_branch("main")
            main_sha = main_branch.commit.sha
            
            branch_name = f"auto-tool/{tool_name}-{uuid.uuid4().hex[:6]}"
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_sha)
            
            remote_path = f"src/tools/dynamic/{filename}"
            repo.create_file(
                path=remote_path,
                message=f"feat(agent): add new tool {tool_name}",
                content=code_content,
                branch=branch_name
            )
            
            pr = repo.create_pull(
                title=f"[Agent] New Tool: {tool_name}",
                body=f"## Purpose\n{purpose}\n\nGenerated by AI Agent Self-Evolution Loop",
                head=branch_name,
                base="main"
            )
            
            return {
                "status": "success", 
                "message": f"PR Created: {pr.html_url}",
                "pr_url": pr.html_url
            }

        except GithubException as e:
            message = e.data.get('message', str(e)) if hasattr(e, 'data') else str(e)
            return {"status": "error", "message": f"GitHub API Error: {message}"}
        except Exception as e:
            return {"status": "error", "message": f"Internal Error: {e}"}
